---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse) 
library(dplyr)
library(janitor) 
```


```{r}
smoking <- read_csv("data/smoking_and_ecigarettes_by_location.csv") 
overall <- read_csv("data/scotland_overall_survey.csv") %>% 
  clean_names() 
local <- read_csv("data/scottish_survey_local.csv") %>% 
  clean_names()
```

```{r}
local_filtered <- local %>% 
  select(-units, feature_code) %>%
  filter(scottish_health_survey_indicator == c("Any cardiovascular condition: Has a cardiovascular condition", "Smoking status: Current smoker")) %>% 
    filter(measurement == "Percent")
```

```{r}
local_two <- local %>% 
  select(-units, -feature_code) %>% 
  filter(scottish_health_survey_indicator == c("Self-assessed general health: Bad/Very bad", "Smoking status: Current smoker")) %>% 
  filter(measurement == "Percent") %>% 
  pivot_wider(names_from = scottish_health_survey_indicator, 
              values_from = value) %>% 
  drop_na() %>% 
  clean_names() 
```


```{r}
local_filtered_pivot <- local_filtered %>% 
  pivot_wider(names_from = scottish_health_survey_indicator, 
            values_from = value) %>% 
  drop_na() %>% 
  clean_names() 
```

```{r}
library(Hmisc) 

local_filtered_matrix <- local_filtered_pivot %>% 
  select(smoking_status_current_smoker, any_cardiovascular_condition_has_a_cardiovascular_condition) 

local_filtered_matrix <- as.matrix(local_filtered_matrix) 

class(local_filtered_matrix)

rcorr(local_filtered_matrix, type = c("pearson"))   
```

```{r}
library(ggpubr) 

ggscatter(local_filtered_pivot,
          x = "smoking_status_current_smoker", 
          y = "any_cardiovascular_condition_has_a_cardiovascular_condition", 
          add = "reg.line", 
          conf.int = TRUE, 
          cor.coef = TRUE, 
          cor.method = "pearson", 
          xlab = "Percentage of smokers", 
          ylab = "Percentage of those with a cardiovascular condition") 

```

Checking for normality 

```{r}
ggdensity(local_filtered_pivot$smoking_status_current_smoker, fill = "lightgray") 
ggqqplot(local_filtered_pivot$smoking_status_current_smoker) 

library(rstatix)

local_filtered_pivot %>% 
  shapiro_test(smoking_status_current_smoker)
```

```{r}
ggdensity(local_filtered_pivot$any_cardiovascular_condition_has_a_cardiovascular_condition, fill = "lightgray") 
ggqqplot(local_filtered_pivot$any_cardiovascular_condition_has_a_cardiovascular_condition) 

local_filtered_pivot %>% 
    shapiro_test(any_cardiovascular_condition_has_a_cardiovascular_condition)
```

```{r}

```


```{r}
ggscatter(local_two,
          x = "smoking_status_current_smoker", 
          y = "self_assessed_general_health_bad_very_bad", 
          add = "reg.line", 
          conf.int = TRUE, 
          cor.coef = TRUE, 
          cor.method = "pearson", 
          xlab = "Percentage of smokers", 
          ylab = "Percentage of those with a cardiovascular condition") 
```


The mean percent of smokers has not decreased since the popularisation of e-cigarettes The mean percent of smokers has decreased since the popularisation of e-cigarettes 

```{r}
library(infer) 
```

Cigarettes are not statistically significantly different in 2008 from 2019 
Cigarettes are statistically significantly different in 2008 from 2019 

```{r}
overall_filtered_smoking_usage <- overall %>% 
  filter(scottish_health_survey_indicator == c("Smoking status: Current smoker", "E-cigarette use: Currently using")) %>% 
  filter(measurement == "Percent") 

overall_pivoted <- overall_filtered_smoking_usage %>% 
  pivot_wider(names_from = scottish_health_survey_indicator, values_from = value) %>% 
  clean_names() %>% 
  group_by(date_code) %>% 
  filter(date_code == 2014 | date_code == 2019) %>% 
  pivot_wider(names_from = date_code, values_from = smoking_status_current_smoker) 

smoke_difference <- overall_pivoted %>%
  mutate(diff_smoke = `2008` - `2019`) %>% 
  filter(!is.na(diff_smoke))
```

```{r} 
null_distribution <- smoke_difference %>% 
  specify(response = diff_smoke) %>% 
  hypothesize(null = "point", mu = 0) %>% 
  generate(reps = 10000, type = "bootstrap") %>% 
  calculate(stat = "mean") 
```

