---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse) 
library(janitor) 
```

```{r}
read_csv()
```


```{r}
life_satisfaction <- scotland_survey_cleaned %>% 
  select(date_code, scottish_health_survey_indicator, sex, percent, lower_confidence_limit_95_percent, upper_confidence_limit_95_percent) %>% 
  filter(scottish_health_survey_indicator == "Life satisfaction: Above the mode (9 to 10-Extremely satisfied)" | scottish_health_survey_indicator == "Life satisfaction: Below the mode (0-Extremely dissatisfied to 7)" | scottish_health_survey_indicator == "Life satisfaction: Mode (8)")  

life_satisfaction
```


```{r}
life_satisfaction %>% 
  filter(sex == "All") %>% 
  ggplot(aes(date_code, percent, colour = scottish_health_survey_indicator)) + 
  geom_line() + 
  geom_point() + 
  scale_x_continuous(breaks = c(2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019)) + 
  geom_ribbon(aes(ymin= lower_confidence_limit_95_percent, ymax= upper_confidence_limit_95_percent), linetype = 1, alpha = 0.1)
```

